### PR TITLE
Test styling

### PR DESCRIPTION
**Pull request by jashapiro**
While the main purpose of this is to test the `/style` command, I did that by starting a contributing document, which just includes styling instructions for now.

### CODE REVIEW

**Comment by jashapiro** [comment]
Okay, that didn't work.

Apparently I need to have my organization membership public, which I for some reason did not: https://github.com/orgs/community/discussions/18690

Let's try it again.

**Comment by jashapiro** [comment]
Success! 

It looks like @allyhawkins (and anyone else) will need to be able to go to https://github.com/orgs/AlexsLemonade/people and make sure that their membership is set to "public" to use this feature.

**Comment by allyhawkins** [comment]
> It looks like @allyhawkins (and anyone else) will need to be able to go to https://github.com/orgs/AlexsLemonade/people and make sure that their membership is set to "public" to use this feature.

Done!

**Comment by jashapiro** [comment]
> > It looks like @allyhawkins (and anyone else) will need to be able to go to https://github.com/orgs/AlexsLemonade/people and make sure that their membership is set to "public" to use this feature.
> 
> Done!

Want to give it a shot?

**Comment by jashapiro** [comment]
Do we want to put these changes in and try to keep it the code up to date with said styling? Requesting a rereview so we can merge this if desired.

**Pull request merged**
